### ISSUE TITLE
Unreadable

### ISSUE THREAD

**Issue by rmcgwier** [GlodBlock/OreVisualDetector#1]
I can't read what it says when I try to use it. What might be the problem
![2022-07-29_11 43 09](https://user-images.githubusercontent.com/21150891/181815856-a12e9890-e20d-4c32-9fc6-6900af5dfb1f.png)
.

**Comment by CrossVas** [comment]
For those who encountered this issue, just install BetterFonts ([TTFR](https://www.curseforge.com/minecraft/mc-mods/truetype-font-replacement))

**Comment by rmcgwier** [comment]
BetterFonts didn't work but when I checked other font mods I found Smooth Font which did. Thanks.
